package com.genit.customersupport.enums;

public enum AiIntent {

	OTHER, GENERAL_QUERY, ORDER_DELAY, ORDER_CANCELLATION, ACCOUNT_ISSUE, REFUND_REQUEST, PRODUCT_ISSUE, DELIVERY_ISSUE,
	PAYMENT_ISSUE, TECHNICAL_ISSUE, RETURN_REQUEST
}